apiVersion: v1
data:
  admin.password: JDJhJDEwJFhPNGNQZC9jLnJMZ3pOaDJUL29tWC5GQ24wTzkyLzRHVGpFb3M0MERGU1BOVHBjdGNIYWND
  admin.passwordMtime: MjAyMi0wMS0xN1QwODoxMjozOFo=
  server.secretkey: L1doZEwvR3BweG9LbTZwSkd0REFyZ24yVmtZeE1nWHphQVJCZ0JDZFdhZz0=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
