kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mets
networking:
  podSubnet: "10.242.0.0/16"
  serviceSubnet: "10.93.0.0/16"
  ipFamily: ipv4
nodes:
- role: control-plane
  image: kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
  #image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
- role: control-plane
  image: kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
  #image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
- role: control-plane
  image: kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
  #image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
- role: worker
  image: kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
  #image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
- role: worker
  image: kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
  #image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
#- role: worker
#  image: kindest/node:v1.23.13@sha256:ef453bb7c79f0e3caba88d2067d4196f427794086a7d0df8df4f019d5e336b61
  #image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315

#- role: worker
#  kubeadmConfigPatches:
#  - |
#    kind: JoinConfiguration
#    nodeRegistration:
#      kubeletExtraArgs:
#        node-labels: "ingress=true"
#        register-with-taints: "ingress=true:NoSchedule"
#- role: worker
#  kubeadmConfigPatches:
#  - |
#    kind: JoinConfiguration
#    nodeRegistration:
#      kubeletExtraArgs:
#        node-labels: "ingress=true"
#        register-with-taints: "ingress=true:NoSchedule"
#- role: worker
#  kubeadmConfigPatches:
#  - |
#    kind: JoinConfiguration
#    nodeRegistration:
#      kubeletExtraArgs:
#        node-labels: "monitoring=true"
#        register-with-taints: "monitoring=true:NoSchedule"
#- role: worker
#  kubeadmConfigPatches:
#  - |
#    kind: JoinConfiguration
#    nodeRegistration:
#      kubeletExtraArgs:
#        node-labels: "monitoring=true"
#        register-with-taints: "monitoring=true:NoSchedule"

