apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: runenv
        value: {{ .Values.runenv }}
      - name: gitrepo
        value: {{ .Values.gitrepo }}
      - name: gitbranch
        value: {{ .Values.gitbranch }}
    path: argocd-applications
    repoURL: {{ .Values.gitrepo }}
    targetRevision: {{ .Values.gitbranch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
