apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: haproxy
  project: default
  source:
    path: argocd-yaml/haproxy
    repoURL: {{ .Values.gitrepo }}
    targetRevision: {{ .Values.gitbranch }}
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
        - values-{{ .Values.runenv }}.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
