apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keydb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:      
    path: argocd-yaml/keydb
    repoURL: {{ .Values.gitrepo }}
    targetRevision: {{ .Values.gitbranch }}
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.runenv }}.yaml
  syncPolicy:
{{- if ne .Values.runenv "prod" }}
    automated:
      prune: true
      selfHeal: true
{{ end }}
    syncOptions:
    - CreateNamespace=true
