apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: argocd-yaml/prometheus
    repoURL: {{ .Values.gitrepo }}
    targetRevision: {{ .Values.gitbranch }}
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.runenv }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
